import type { Metadata } from 'next';
import { Open_Sans } from 'next/font/google';
import './globals.css';

const openSans = Open_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={`{openSans.className} min-h-screen antialiased`}>
				<main className='bg-slate-50 w-full min-h-screen mx-0 flex-grow p-6 sm:p-8 md:p-12 lg:p-20'>
					{children}
				</main>
			</body>
		</html>
	);
}
